config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get '/home/about' => 'homes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true, length:  { maximum: 50 }
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      user_path(current_user.id) # ログイン後に遷移するpathを設定
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    def new
    	@book = Book.new
    end
    def create
    	@book =Book.new(book_params)
        @book.user_id = current_user.id
    	if @book.save
            flash[:notice] = "You have creatad book successfully."
    		redirect_to book_path(@book.id)
    	else
            @user = current_user
            @books = Book.all
    		render:index
    	end
    end
    def index
        @user = current_user
        @book =Book.new
        @books = Book.all
    end
    def show
        @postbook =Book.new
        @book = Book.find(params[:id])
        @user = @book.user

    end
    def edit
        @book =Book.find(params[:id])
        if @book.user.id != current_user.id
            redirect_to books_path
        end
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "You have updated book successfully."
            redirect_to book_path(@book.id)
        else
            render:edit
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end
    private

    def book_params
    	params.require(:book).permit(:title, :body, :user_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
	  	@user = User.find(current_user.id)
	  	@users = User.all
	  	@book = Book.new
	end

	def show
	  	@user = User.find(params[:id])
	  	@book = Book.new
	  	@books = @user.books
	end

	def edit
	    @user = User.find(params[:id])
	    if @user.id != current_user.id
            redirect_to user_path(current_user.id)
        end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		   flash[:notice] = "You have creatad book successfully."
		   redirect_to user_path(@user.id)
	    else
	    	render :edit
	    end
	end

	private
    def user_params
    	params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Editing Books</h1>
		<% if @book.errors.any? %>
			<%= pluralize(@book.errors.count,"error") %>
		    <ul>
		        <% @book.errors.full_messages.each do |message| %>
	            <li><%= message %></li>
		        <% end %>
		    </ul>
		<% end %>

		<%= form_for(@book) do |f| %>
		<h5>Title</h5>
		<%= f.text_field :title %>
		<h5>Option</h5>
		<%= f.text_area :body %>
		<div class="btn"><%= f.submit 'Update Book' %></div>
		<% end %>
		<%= link_to "Show", book_path(@book.id) %>
		<%= link_to "Back", books_path %>
	</div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<%= pluralize(@book.errors.count,"error") %>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<div class = "container">
	<div class = "row">
		<div class="col-xs-3">
			<%= render '/all', {user: @user, book: @book} %>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class = "table">
				<tr>
					<th></th>
					<th>Title</th>
					<th>Option</th>
				</tr>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user.id) do %>
							<%= attachment_image_tag book.user, :profile_image,format: 'jpeg', fallback: 'no_image.jpg', size: '40x40'%>
						<% end %>
						</td>
					<td><%=link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class = 'container' >
	<div class="row">
		<div class="col-xs-3">
			<%= render '/all', {user: @user, book: @postbook} %>
		</div>
		<div class="col-xs-9">
			<h1>Book detail</h1>
			<table class="table">
				<tr>
					<td><%= attachment_image_tag @user, :profile_image, format:'jpeg', fallback: 'no_image.jpg', size: '40x40' %><br>
						<%= link_to @user.name, user_path(@user.id) %>
					</td>
					<td><%= @book.title %></td>
					<td><%= @book.body %></td>
				    <% if @book.user.id != current_user.id %>
				    <% else %>
						<td ><%= link_to 'Edit', edit_book_path(@book.id), class:"btn btn-success" %></td>
						<td ><%= link_to 'Destroy',book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-danger"%></td>
					<% end %>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<div class= "container">
	<h1>Welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>!</span></h1>
</div>

app/views/homes/top.html.erb
<div class= "container">
	<div class= "row">
        <div class= "top-massage col-md-offset-3 col-md-6">
			<h1>welcome to<span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
			<p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
			<p>you can share and exchange  your opinions , inpressions , and emotions</p>
			<p> about various books!</p>
			<div class="btn-wrapper">
				<div class="row">
					<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1"%>
				</div>
				<div class="row">
					<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value) %>
<% end %>

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html> -->
<html>
  <head>
    <title>SampleAppDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <header>
        <div class="container">
          <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
          </nav>

            <% if user_signed_in? %>
                  <nav>
                    <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home"%></li>
                        <li><%= link_to "Users", users_path, class: "glyphicon glyphicon-user"%></li>
                        <li><%= link_to "Books", books_path, class: "glyphicon glyphicon-book"%></li>
                        <li><%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out"%></li>

                    </ul>
                  </nav>

            <% else %>
                  <nav>
                    <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to "Home", root_path, class: "glyphicon glyphicon-home"%></li>
                        <li><%= link_to "About", home_about_path, class: "glyphicon glyphicon-link"%></li>
                        <li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit"%></li>
                        <li><%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in"%></li>

                    </ul>
                  </nav>

            <% end %>
        </div>
      </header>
      <%= render 'layouts/notifications' %>
  <%= yield %>


  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class= "container">
	<h2>User info</h2>
	<%= form_for(@user) do |f| %>
		<% if f.object.errors.any? %>
		<%= pluralize(f.object.errors.count,"error") %>
		    <ul>
		        <% f.object.errors.full_messages.each do |message| %>
		            <li><%= message %></li>
		        <% end %>
		    </ul>
		<% end %>
		<strong>Name</strong>
		<%= f.text_field :name %>
		<p>Image</p>
		<%= f.attachment_field :profile_image %>
		<strong>Introduction</strong>
		<%= f.text_area :introduction %><br>
		<%= f.submit 'Update User' %>

	<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render '/all', user: @user, book: @book %>
	    </div>
	    <div class="col-xs-9">
				<h2>Users</h2>
				<table class="table">
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="1"></th>
					</tr>
						<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag @user, :profile_image,format: 'jpeg', fallback: 'no_image.jpg', size: '40x40'%></td>
						<td><%= user.name %></td>
						<td><%= link_to 'Show', user_path(user.id) %></td>
					</tr>
						<% end %>
				</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% if @user.errors.any? %>
<%= pluralize(@user.errors.count,"error") %>
    <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<% if user_signed_in? %>
<div class = "container">
	<div class = "row">
		<div class = "col-xs-3">
			<%= render '/all', user: @user, book: @book%>
		</div>
		<div class = "col-xs-9">
			<h2>Books</h2>
			<table class = "table table-striped">
				<tr>
					<th></th>
					<th>Title</th>
					<th>Option</th>
				</tr>
				<% @books.each do |book| %>
				<tr>
					<td><%= attachment_image_tag @user, :profile_image,format: 'jpeg', fallback: 'no_image.jpg', size: '40x40'%></td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
		        </table>
		</div>
	</div>
</div>
<% end %>